[package]
name = "austi/fps-test"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7"
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.1.0"
Timer = "sleitnick/timer@1.1.2"
Cmdr = "evaera/cmdr@1.12.0"
ZonePlus = "imavafe/zoneplus-reupload@3.2.0"
character-animate = "egomoose/character-animate@0.0.3"